apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springpi
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
        autoscaling.knative.dev/window: "30s"
    spec:
      containers:
      - image: ghcr.io/alexandreroman/spring-on-k8s@sha256:172455d6d3d1b9e3e66efeb348b80d50119640400565effa2b699b4579102bee
        imagePullPolicy: Always
        env:
        - name: SPRING_CONFIG_IMPORT
          value: configtree:/etc/config/
        volumeMounts:
        - mountPath: /etc/config
          name: config
      volumes:
      - name: config
        configMap:
          name: config
