apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spring-on-k8s
resources:
- https://raw.githubusercontent.com/alexandreroman/spring-on-k8s/main/k8s/base/namespace.yml
- kservice.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config
  literals:
  - app.message=Hello Raspberry Pi!
images:
- name: ghcr.io/alexandreroman/spring-on-k8s
  digest: sha256:2ea1acc3117412c1969dbc9d4cb8e1383eb25810efd490efc23c5e673068e992
