apiVersion: v1
kind: Namespace
metadata:
  name: rpilab-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rpilab
  namespace: rpilab-system
spec:
  interval: 5m
  url: https://github.com/alexandreroman/rpilab
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rpilab-addons
  namespace: rpilab-system
spec:
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: rpilab
  path: addons
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rpilab-apps
  namespace: rpilab-system
spec:
  interval: 3m
  sourceRef:
    kind: GitRepository
    name: rpilab
  path: apps
  prune: true
  timeout: 10m
