apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-redis
spec:
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    tag: "20.6.3"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bonjour-db
spec:
  chartRef:
    kind: OCIRepository
    name: bitnami-redis
  interval: 30m
  values:
    architecture: standalone
    auth:
      existingSecret: bonjour-db-password
    serviceBindings:
      enabled: true
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: bonjour-db-password
spec:
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
