apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: bonjour-config
spec:
  name: config
  service:
    apiVersion: v1
    kind: Secret
    name: bonjour-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: bonjour
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: bonjour-db
spec:
  name: db
  service:
    apiVersion: v1
    kind: Secret
    name: bonjour-db-redis-svcbind
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: bonjour
