apiVersion: v1
kind: Secret
metadata:
  name: hello-rpilab-config
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
type: Opaque
stringData:
  provider: gitops
  type: config
  app.info.server.hostname: rpilab.dev
  app.ninjas.api.key: Ma06DFYKVNFMtlpZtzIFfA==mHifHTA7ksfQmirb
  app.weather.api.key: 535f2d22d23e48aea2f173609232511
  management.tracing.sampling.probability: "1"
  management.otlp.metrics.export.step: 1m
