apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-rpilab
resources:
- namespace.yaml
- otel.yaml
- otel-sealed-secret.yaml
- database.yaml
- app-sealed-secret.yaml
- service-binding.yaml
- kservice.yaml
images:
- name: ghcr.io/alexandreroman/hello-rpilab
  digest: sha256:106a000593e87909962e825afafb8647dfb516bcda6de8803faa71063b6c76e6
