apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: hello-rpilab-config
spec:
  name: config
  service:
    apiVersion: v1
    kind: Secret
    name: hello-rpilab-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hello
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: hello-rpilab-db
spec:
  name: db
  service:
    apiVersion: v1
    kind: Secret
    name: hello-rpilab-db-redis-svcbind
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: hello
