apiVersion: batch/v1
kind: CronJob
metadata:
  name: resumebot-audit
spec:
  schedule: "0 23 * * *"
  successfulJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 2
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: audit
            image: ghcr.io/alexandreroman/resumebot-audit
            env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: resumebot-db-redis-svcbind
                  key: host
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: resumebot-db-redis-svcbind
                  key: port
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resumebot-db-redis-svcbind
                  key: password
