apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicebinding-knative-role
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  - configurations
  verbs:
  - get
  - list
  - watch
  - update
  - patch
