---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: redir
spec:
  encryptedData:
    REDIS_HOST: AgBMRQ8wJy9tRqaBPB5Pia8IJhWbAvqs5qCGaK9qmIYGpJjixnKB23P1Jg6I9hbA+KBjIQ3mZJgzs+YAbzi3Y3puDIJ+MrHiMom5LjukqzCvVOcc2ywwNWsCFQ825im04V33GDhD5awp/eEBowRv4uK9/C6rFWgzdtIycWChd1w0SeNbJpon+NBTFzPAaaKNlWd3z6N5xXzctTApgEcJFZt/YLIw6d31H9gXe1MWEWeZUeh+6g+qK1de0PXtoIhJFx6sNi+2Ev1pyb5QKdEiBkS4CwixpuqVeYLBaz5uyFswtLWqUkwYC4coNGGnhfAFmJo1B+giiS3T4A4mN+vRK2W9mbaVILFomQj93NV5voQgwYlpo/JAVhZFJNni3HEA9Ri1hGREFXsJT3jI0FuGBO3PSTHoHpOvrRkiCmy5ZRE7mEIa+rectKnGsXKO5WVHkBEKgsNfPAg0RU4iX46cZuzhUCEf7pfwiffGULgFSGQ8nV7MaOYMPlIAcGLdlpFGoP+eTiz4KzWsrTNbRZIxwDjLeAt5KziWGqVOgx3S+gpLhIcJb8sZEThiWiIBuCtTX9W9v+n9PEEwYXCrcpoqaW3qTX/hHcrs+TpzpDo0yI2KverJtU0/5R+/XwALhTveh7XhEiet3BhMR8ETskaA7VgmFN3RnwiXaKyxBTqzrRW674y2hdhzMSb+EeWtP9nG7h+0wkWjRiKgqkTRziEokX6AEtns3++uJ9H+oMPmKA==
    REDIS_PASSWORD: AgCRFTYX3yDXi+tgI5UsKzVZqwDkNZkIuCcPkAjgigQiq1TfjoZcqLdia1tYZsxeC+/W2/oZ2r09k/5XDbpavL6bOm/xZQP5dVDpuSLkn2ck02+VNP2kzO5uPaMgwKO+ilANdO3ZoF8gs7c6KrpwAE+CTbCr7RmVUoNXCYvMru0pVmSepBE3EkownP6uaIPe2ZPJF+XeG265Ha8VzVgFWeKp0rUKrsg5ZVFJv3C9sBx6vmNV/vldEThjfU94WrfQWnpUbsPoLhQoKJfycW94MozhtHAigwxaTkuMEz4WxSbL5436TMYZAsj9RarY5tEqMHK88QEIGtvGsSN+MP/EuKhL3RVITqmm6wyH6mo7Mi035kWyxpNq21eaQvAIKNqW0lIpl8vHPhLmq/6mcNIz4+pX6xNyViyGMHVTmle+2mSAh6aS0wdLDATjIcycC1uttC7VHNbaiuAPGEWBWm4yada7OCPuSKzCiWDzcw5o21QToStQcuOS/BO91GqoGf7U9g1vPnPwAJFmjmZhrbEEwaB56ON9ofSYei6aJiVpxHVqSAHNS7mhWHs/OrYpNsasDjeyBPHwqWV7lWh9uR4DSTX41RlYA7zRBPQ/UBx0U5hFWlHL31sdnDRDsuL1Ardb7rEESx2xiIWdpacbvZvQ2IHC4mVnTPGTP2TR4KulLXytyKoDFivmfvmJgtCDJeot5IScdJkEKOHT7+jn827HqYymisFgfwcxNE8gyBrmOrGTwuzMNgqtVhahZ7n6AFa9oc+xjlK2+H97F0jl9iOcGYI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: redir
    type: Opaque
