[[redirects]]
slug = "linkedin"
url = "linkedin.com/in/alexandre-roman"

[[redirects]]
slug = "github"
url = "https://github.com/alexandreroman"

[[redirects]]
slug = "bluesky"
url = "https://bsky.app/profile/alexandreroman.fr"
