apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: temporal-story-config
spec:
  name: config
  service:
    apiVersion: v1
    kind: Secret
    name: temporal-story-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: temporal-story
