---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: yao
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgBAKHAjvgSM/AVdLNE44T0muGOFGLy3ftazeGkWrUDOe5hoXVXXFwQVHMdCYR88CfSZuU1ZqJJYUIfUonTlUi5zAwhtH2RUmvU8fhRHySOAHv1tZwUjQJvSFlxvasC+uICmVOkV6kLkwhvPJsivfldOvzmn1rU1+M7CtUO8j+WhnteD0GRCBnxRSGMDvzVHEEZLYdhSznjHrs76dTElXJfCz7ri10LSsjWITmtcdY8wExrJwGHQ4KXSXPyJBK3k0vEXGES1Wp413Tl9/G7ovqRysREVOamqovygWznMBGZZIbsI72J7+0B0Ua4gL3Y/a/N2Lx6GMvZJ1UwuLxHBEylrbV4e5pAcom5wd6+y822fspy7T+8UOSzTbc0A1UKu8nZpHJU2RQfM+PDZmZJK27MaDCX8X180FS6t4sx/u/VfK6IFYpzSXB32jMYxTbM2D2PKLZB2MFGO02W4ZS17+UuvWma37flxvV8q4AQWb950tbgMG762QAu03cPeD83bKD+/8WKba2Sz3slWXPHK2C+tNzsZu5u1KwMGb5RIv5u1bLBVrGWfQ71nL5G7YSur2DytxDcs0ES61SL1t0HodKqnFBQvwDoMS2JKFQCgaoXg65rroB/RxUydxmNpMTxnwwzpPMkP0ZMfjymFQF90HaPfPfM344rXJjXL43XBTcRFnAqoYzHb/6KS2nlhiHZNS6pBu1+mYxgGHlLdU8WlHhaGPZ2arlgSu+56dSNtQV1/3M5XYSZrk16iOkVIiDMdJ91ZptEIs+8jlR00UcMazpo/cvP5wouIWdEVmlmAjDWerwsM6Liphh5tB9HbP690ooTHWAffj5pwjtohVms=
    TELEGRAM_BOT_TOKEN: AgBX5JVNjpKkaZJC/K9gHeY1k5emiO+V/o+NCOfkt/cIny4ELFgJe9JO8BzMT0AjfyaaHh7qZy9YPn9kOQ7Q9x4NLnhujVA1k+2l+Y8TB+xEdsDGL0fn/PIeK6PuJJLToilXoxZuXMkaDRNDSlmlvzucPLN/e8i77+fWb+YBrUX/QKX8/pqeET+QJL4v0OaYPKOLmzMN2wj0ZwF0zlhd6l7vjIUWdipq4EvR7KZ783BCz6l9zevlHjTfDOv+j0RxPRYNqTY/3SStMhLDyMUteHB10MqQrsA5CSnKk5HEHHdgMunHz2l1ESId7P9XLLd6Do/xsDpj5+Ctt9ppa6DApUUPoHIieX7+WtjYHvAa2UcWsGUODTSE8+2e9KkzN0nphSSvpPJYfHGuAt6EXq8A3U1WtNXMQjwboXIAi+IRKK1usP7l4xBjk4cFUlGWi94AuIrd2OEXJmhztsUzmMvojmnW4NDXAtdk+HJCv4iHjenvRvxIH+ppdTRIxQnmgLBvw4hSKGh2RQC/do+WR53uf7Ls8pJTW4uE+a+7vKwmbircPlZlP8wD7P76w3QK6PwTvP7IbjdTTkZI8ikyzXZuCdRCciRyFDFM/PejWNKvXrO0jL3KG/1xH3eghX7gGKZCt5SqtXDL2a70SCOzM2FBMPpc2kbLKAIsWEtHhDNDAqyEqvlGJixnUd6lKrlHihAdFuDz+QylZ5lhIH5Je9BzwleiIiq5Ji3lQwTN1Zz5IvM45rZPeG5GVatahw48OmVC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: yao
    type: Opaque
