apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yao
resources:
- namespace.yaml
- deployment.yaml
- app-sealed-secret.yaml
- pvc.yaml
configMapGenerator:
- name: yao
  files:
  - config.toml
