apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: html-assistant-config
spec:
  name: config
  service:
    apiVersion: v1
    kind: Secret
    name: html-assistant-config
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: html-assistant
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: html-assistant-db
spec:
  name: db
  service:
    apiVersion: v1
    kind: Secret
    name: html-assistant-db-redis-svcbind
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: html-assistant
