apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: contour-external
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: projectcontour.io/contour-external/contour
