apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: rpilab-router-config
spec:
  name: config
  service:
    apiVersion: v1
    kind: Secret
    name: rpilab-router-config
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: rpilab-router
